### ISSUE TITLE
Use this with built SilentXMR exe?

### ISSUE THREAD

**Issue by Night1099** [UnamSanctam/UnamDownloader#10]

**Comment by UnamSanctam** [comment]
Yes you can use this with any file.

**Comment by Night1099** [comment]
When I run the exe through the UnamDownloader, the new file doesnt run the miner. Im probably missing something, thanks for fast reply.

**Comment by UnamSanctam** [comment]
But it downloads it correctly?

**Comment by Night1099** [comment]
I believe so, ive ran the file by itself after I use your SilentXMR Builder, it starts the miner, i upload the built exe to GitHub, copy the direct download link, click build, I see it boot up powershell for a second or two, and then nothing happens. I see that the SilentXMR builder should have a crypter in it to bypass defender, my defender sees it immediately.

**Comment by UnamSanctam** [comment]
So you build the miner with "Bypass Windows Defender"? Do you also run the downloader as administrator then? You can enable "Add Windows Defender exclusions" and "Run as administrator" in the downloader for it to "bypass" Windows Defender.

No powershell window should ever appear, what Windows version and what version of the downloader are you using?

**Comment by Night1099** [comment]
I misspoke "Add windows defender Exclusions" "Run as admin" require admin privileges, I want to use Unam too get through defender without detection without admin privileges I assumed a crypter in SilentXMR meant that. Also a powershell window window doesnt show up on my screen I meant I see it in the task viewer. :) Windows 10 and latest downloader

**Comment by UnamSanctam** [comment]
Since the miner is a public and open source project it gets detected after while, the only way to get it undetected would be if you bought a really really good .NET 64-bit crypter or obfuscator, that's how it is with any public project you can find.

**Comment by Night1099** [comment]
Gotcha, I misunderstood, thanks for your patience have a good one :)
