### ISSUE TITLE
download file

### ISSUE THREAD

**Issue by welltom233** [UnamSanctam/UnamDownloader#11]
which file exchanger to use for instant file uploads?

**Comment by UnamSanctam** [comment]
https://github.com/UnamSanctam/UnamDownloader/issues/2, Best is to use something like BitBucket but it can be hard to use so you can try other things like Discord.

**Comment by welltom233** [comment]
спасибо

> Читайте здесь: [№2](https://github.com/UnamSanctam/UnamDownloader/issues/2) , лучше всего использовать что-то вроде BitBucket, но это может быть трудно использовать, поэтому вы можете попробовать другие вещи, такие как Discord.

**Comment by welltom233** [comment]
the downloader works through Discord. but I still did not understand how to glue the downloaded file and another program for masking.

**Comment by UnamSanctam** [comment]
You can download the program used for masking as well. A downloader is a form of binder.

**Comment by welltom233** [comment]
> Вы также можете скачать программу, используемую для маскировки. Загрузчик - это форма связующего.

could you recommend such a program?

**Comment by UnamSanctam** [comment]
What program are you trying to bind the downloader with? You can download that program as well with the downloader.

**Comment by welltom233** [comment]
> Какой программой вы пытаетесь привязать загрузчик? Вы также можете скачать эту программу с помощью загрузчика.
I just need to glue two exe + exe files.
sorry i'm just learning

**Comment by UnamSanctam** [comment]
Yes, either you could use a file binder which would increase detections a lot or you can use the downloader to do it. Add both files you want to bind to the downloader and it will download and start both of them.

**Comment by welltom233** [comment]
> Да, вы можете либо использовать связыватель файлов, который значительно повысит обнаружение, либо вы можете использовать загрузчик для этого. Добавьте оба файла, которые вы хотите привязать, к загрузчику, и он загрузит и запустит их оба.

почему то без загрузчика 19 обнаружений. а с загрузчиком 23

**Comment by UnamSanctam** [comment]
Usually the only important detection to get around is Windows Defender since most others will detect things at runtime or sandboxes.
