### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by FireHack7z** [UnamSanctam/UnamDownloader#13]
how to start an executable, is its visibility disabled? because the mandark library does not allow disabling the software display

Can you help me ?

**Comment by UnamSanctam** [comment]
How to start what executable? You can not hide the GUI from a program in any real easy way if the program does not have something built in to do so. You can hide the console if the program only has that.

**Comment by FireHack7z** [comment]
Yes its a console app

**Comment by UnamSanctam** [comment]
What are you trying to start it as or with? Your own application? If you mean the downloader then the downloader is just a powershell host so that can't be done of course but the https://github.com/UnamSanctam/UnamBinder has an option to "Hide Console Window" when adding a file.
