### ISSUE TITLE
Defender 

### ISSUE THREAD

**Issue by Byblack36** [UnamSanctam/UnamDownloader#14]
defender detects the created file

bunun üstesinden nasıl gelebilirim

**Comment by UnamSanctam** [comment]
Do you build it as native? And if it detects it try rebuilding it.

**Comment by Byblack36** [comment]
I couldn't understand my english is not very good

**Comment by UnamSanctam** [comment]
Try rebuilding it with "Native" selected.

**Comment by Byblack36** [comment]
ok i will try

**Comment by Byblack36** [comment]
defender is caught again what should i do

**Comment by UnamSanctam** [comment]
Rebuild it, your files MD5 checksum can be registered in a database, meaning that the file or code itself probably isn't detected but just the MD5 checksum/hash of the file.

**Comment by Byblack36** [comment]
so what should i do

**Comment by UnamSanctam** [comment]
Rebuild the file.
