### ISSUE TITLE
How to build it as Native

### ISSUE THREAD

**Issue by kgnfth** [UnamSanctam/UnamDownloader#25]
There is no option

**Comment by UnamSanctam** [comment]
It always builds as native.

**Comment by kgnfth** [comment]
@UnamSanctam then how to build as Managed ? 😂

https://github.com/UnamSanctam/UnamDownloader/wiki#build-file-type

**Comment by UnamSanctam** [comment]
Ah yeah that was removed.

**Comment by kgnfth** [comment]
Okey thx
