### ISSUE TITLE
Where to host files besides Discord and Github?

### ISSUE THREAD

**Issue by Nigward8174** [UnamSanctam/UnamDownloader#31]
Where to host files besides Discord and Github? I know anonfiles, file io, mediafire and such wouldnt be a good options, so where could I host em

**Comment by UnamSanctam** [comment]
Apart from Discord/GitHub you could potentially use BitBucket, possibly Google Drive (use https://sites.google.com/site/gdocs2direct/ and then add `&confirm=t` to the final URL) or maybe Dropbox (change domain to `dl.dropboxusercontent.com` in share link).
