### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by DogusCyk** [UnamSanctam/UnamDownloader#33]
hey miner and when i bind with a token grabber only the token grabber arrives my miner does not come why

**Comment by DogusCyk** [comment]
I used discord as the link on both

**Comment by UnamSanctam** [comment]
Check if the file is in the destination or not (%Temp% as default).

**Comment by DogusCyk** [comment]
hmm i made a few changes and i think it's fixed maybe it was getting corrupted because the names of the two of them were file i don't know

**Comment by DogusCyk** [comment]
I'm sorry I won't make a request again until I try to solve the problem a little bit.

**Comment by DogusCyk** [comment]
I hope you understand what I'm saying, I'm translating what I wrote

**Comment by UnamSanctam** [comment]
Yeah make sure that they have different filenames (like File1.exe and File2.exe), otherwise they will overwrite each other.

**Comment by DogusCyk** [comment]
yes, that was the problem, thanks
