### ISSUE TITLE
How to use parameters ?

### ISSUE THREAD

**Issue by brmediahub** [UnamSanctam/UnamDownloader#5]
Hey, How can i execute a file with a parameter

**Comment by UnamSanctam** [comment]
You would have to add `-ArgumentList` into the code where it builds the `Start-Process` here: https://github.com/UnamSanctam/UnamDownloader/blob/49aa98cdc3da88aa2ecfd7e011d82fe2d3630a4c/UnamDownloader/Builder.cs#L132
Like so `powershell Start-Process -FilePath '{0}' -ArgumentList 'argument1','argument2','argument3'`

**Comment by brmediahub** [comment]
Perfect and Thank you
