### ISSUE TITLE
Fast download

### ISSUE THREAD

**Issue by samogost** [UnamSanctam/UnamDownloader#65]
Is there a way to make the downloader download the files faster? When opening the downloader file, it has to wait almost 30 seconds before it downloads and opens the file.

**Comment by UnamSanctam** [comment]
Are you sure you don't have the start delay enabled? It downloads it using powershell, so it depends on your internet speed and the size of the file. For me it takes about a second or two to download a miner.

**Comment by samogost** [comment]
> Bạn có chắc là bạn không kích hoạt độ trễ bắt đầu không? Nó tải xuống bằng powershell, vì vậy nó phụ thuộc vào tốc độ internet của bạn và kích thước của tệp. Đối với tôi, mất khoảng một hoặc hai giây để tải xuống một công cụ khai thác.

I don't have start delay enabled. I open the downloader file on VPS, hmm.. is it because I open it on VPS that the download is slow?

**Comment by UnamSanctam** [comment]
What's the internet speed on the VPS? If you try and download the file manually in the browser how long does it take?

**Comment by samogost** [comment]
> What's the internet speed on the VPS? If you try and download the file manually in the browser how long does it take?

Here:
!(https://user-images.githubusercontent.com/111581758/228591200-a2b2f439-7240-482f-9d9a-fac405f2f2c2.png)

**Comment by UnamSanctam** [comment]
And if you manually download the file that you're trying to download then it downloads it fast? Since the downloader uses Powershell then all the downloading is handled directly by Windows so it should be as fast as anything else.

**Comment by samogost** [comment]
> And if you manually download the file that you're trying to download then it downloads it fast? Since the downloader uses Powershell then all the downloading is handled directly by Windows so it should be as fast as anything else.


will it be no problem if i use the github direct download link?

**Comment by UnamSanctam** [comment]
Use the same link as the one you put in the downloader.
