### ISSUE TITLE
Detected by Win defender

### ISSUE THREAD

**Issue by Thepowa753** [UnamSanctam/UnamDownloader#9]
What obfuscation/Scrambling did you suggest?

**Comment by UnamSanctam** [comment]
When building it as "Native" using version 1.3.0?

**Comment by Thepowa753** [comment]
Yup, C 1.3.0. i'll try with 1.3.1

**Comment by Thepowa753** [comment]
1.3.0 C:                             detected
1.3.0 .net:                        detected
1.3.1 C :                             undetected
1.3.1 .net:                         detected
1.3.1 .net bitcrypter:    detected
